import { makeStyles } from "@mui/styles";

export default makeStyles({
    root: {
        top: '0px',
        left: '0px',
        width: '100vw',
        height: '100vh',
        position: 'absolute',
        maxWidth: '100vw',
        minWidth: '100vw',
        maxHeight: '100vh',
        minHeight: '100vh',
        pointerEvents: 'none',
        border: '0px',
        margin: '0px',
        outline: '0px',
        padding: '0px',
        overflow: 'hidden',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        '& .MuiInput-root': {
          color: 'white',
          fontSize: '1.3vmin',
        },
        '& .MuiInput-underline:hover:not(.Mui-disabled):before': {
          borderColor: 'white',
        },
        '& .MuiInput-underline:before': {
          borderColor: 'darkgray',
          color: 'blue',
        },
        '& .MuiInput-underline:after': {
          borderColor: 'white',
          color: 'blue',
        },
        '& .MuiInputLabel-animated:before': {
          color: 'darkgray !important',
          fontSize: '1vmin',
        },
        '& .MuiInputLabel-animated:after': {
          color: 'white !important',
          fontSize: '1vmin',
        },
        '& .MuiInputAdornment-root': { color: 'darkgray' },
      },
      financialsOuterContainer: {
        position: 'absolute',
        left: '50%',
        top: '50%',    
        width: '100vw',
        height: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        transform: 'translate(-50%, -50%)',
      },
      financialsInnerContainer: {
        top: 'unset',
        left: 'unset',
        position:'absolute',
        height: '75%',
        width: '75%',
        minWidth:'75%',
        maxWidth:'75%',
        minHeight:'75%',
        maxHeight:'75%',
        display: 'flex',
        padding: '32px',
        alignItems: 'center',
        flexDirection: 'column',
        pointerEvents: 'all',
        justifyContent: 'center',
        overflow:'hidden',
        margin: 'unset',
        backgroundColor: 'rgb(34, 40, 49)',
      },
      loadingBox: {
        width: '75vw',
        height: '200px',
        color: 'white',
        display: 'flex',
        overflow: 'hidden',
        position: 'relative',
        maxHeight: '80vh',
        transition: 'all 800ms ease 0s',
        borderRadius: '4px',
        flexDirection: 'row',
        pointerEvents: 'all',
        backgroundColor: 'rgb(34, 40, 49)',
      },
      accountHeader: {
        position:'absolute',
        top:'0',
        left:'0',
        marginTop: '10px',
        marginLeft: '16px'
      },
      accountWrapper: {
        flexDirection: 'column',
        justifyContent: 'space-evenly',
      },
      cashWrapper: {
        display: 'flex',
        flexDirection: 'column',
        marginLeft: '5%',
        marginTop: '2.7%',
      },
      chafeBankWrapper: {
        display: 'flex',
        flexDirection: 'column',
        marginTop: '10px',
        marginRight: '5px'
      },

      accountScroll: {
        position: 'fixed',
        justifyContent: 'space-evenly',
        overflowY: 'scroll',
        height: '66%',
        minHeight: '66%',
        maxHeight: '66%',
        width:'17%',
      },
      transactionWrapper: {
        flexDirection: 'column',
        justifyContent: 'space-evenly',
      },
      transactionHeader: {
        position:'absolute',
        top:'0',
        left:'24.5%',
        marginTop: '10px',
      },
      transactionScroll: {
        position: 'fixed',
        justifyContent: 'space-evenly',
        overflowY: 'scroll',
        height: '66%',
        width:'55.8%',
      },
      accountInnerWrapper: { justifyContent: 'space-evenly' },
      accountLeft: {
        flexDirection: 'column',
        marginLeft: '7px',
        paddingTop: '5px',
      },
      accountRight: {
        flexDirection: 'column',
        textAlign:'right',
        alignItems:'right',
        overflow:'hidden',
        marginRight: '5px',
        marginTop: '-50px',
      },
      accountBox: {
        width: '100%',
        maxWidth:'auto',
        minWidth:'auto',
        height: '150px',
        backgroundColor: '#30475d',
        borderRadius: '3px',
        marginBottom: '10px',
        marginTop: '20px',
        // marginLeft: '16px',
      },
      spinner: { color: '#bfbfbf' },
      activeAccountBox: {
        width: '100%',
        maxWidth:'auto',
        minWidth:'auto',
        height: '150px',
        backgroundColor: '#264361',
        border:"0.3px solid white",
        borderRadius: '3px',
        marginBottom: '10px',
        marginTop: '20px',
        
      },
      inputLabel: {
        color: 'darkgray !important',
        '&.focused': { color: 'white !important' },
      },
      leftButton: { float: 'left' },
      rightButton: { float: 'right' },
      transactionBox: {
        position:'relative',
        width: '100%',
        maxWidth:'auto',
        minWidth:'auto',
        // width: '1047px',
        height: '200px',
        backgroundColor: '#30475d',
        borderRadius: '3px',
        marginBottom: '10px',
        marginTop: '20px',
        // marginLeft: '16px',
      },
      transactionDivider: {
        color: '#fff',
        borderColor: 'rgba(255, 255, 255, 255)',
      },
      transactionInnerWrapper: { justifyContent: 'space-evenly' },
      transactionSecondInnerWrapper: {
        display: 'flex',
        justifyContent: 'space-between',
      },
      transactionThirdInnerWrapper: {
        display: 'flex',
        justifyContent: 'space-between',
        float: 'right',
        height: '20%',
      },
      transactionFourthInnerWrapper: {
        display: 'flex',
        justifyContent: 'space-between',
      },
      transactionLeft: {
        marginLeft: '10px',
        paddingTop: '5px',
      },
      transactionRight: {
        flexDirection: 'column',
        textAlign:'right',
        alignItems:'right',
        overflow:'hidden',
        marginRight: '10px',
        marginTop: '-30px',
      },
      transactionSecondMiddleRight: { marginRight: '15px' },
      transactionThirdMiddle: {
        position:'absolute',
        bottom:'-132px',
        margin:'1%',
        width:'98%',
      },
      modal: {
        top: '0px',
        left: '0px',
        width: '100%',
        height: '100%',
        display: 'flex',
        zIndex: '1000',
        position: 'absolute',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(155, 155, 156, 0.475)',
      },
      modal_mainBox: {
        width:'50%',
        minWidth:'50%',
        maxWidth:'50%',
        height: 'auto',
        display: 'flex',
        overflow: 'hidden scroll',
        position: 'relative',
        maxHeight: 'auto',
        minHeight: 'auto',
        backgroundColor: '#30475d',
      },
      transactionMiddleLeft: {
        flex: '33.33%',
        maxWidth: '15%',
        paddingLeft: '10px',
        paddingTop: '5px',
      },
      transactionMiddleMiddle: {
        flex: '33.33%',
        maxWidth: '49.33%%',
        paddingTop: '5px',
      },
      transactionMiddleRight: {
        flex: '33.33%',
        maxWidth: '16.90%',
        paddingLeft: '10px',
        paddingTop: '5px',
        flexDirection: 'column',
        textAlign:'right',
        alignItems:'right',
        overflow:'hidden',
        marginRight: '10px',
      },
});