import { makeStyles } from "@mui/styles";

export default makeStyles({

    clothingHeader: {
        display: 'flex',
        width: '100%',
        height: '5%',
        marginBottom: '2vh',
    },
    clothingHeaderInner: {
        display: 'flex',
        width: '100%',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingLeft: '12px',
        paddingRight: '12px',
    },
    clothingInnerContainerWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        width: '100%',
        height: '100%',
        maxHeight: '92%',
        overflow: 'auto',
    },
    clothingInnerContainer: {
        display: 'flex',
        flexDirection: 'column',
        width: '95%',
        height: 'max-content',
        borderRadius: '3px',
        marginBottom: '3vh',
        backgroundColor: '#30475e',
    },
    clothingInnerContainerHeader: {
        display: 'flex',
        flexDirection: 'column',
        paddingLeft: '1vh',
        paddingBottom: '1.5vh',
    },
    clothingInnerContainerHeaderSlider: {
        display: 'flex',
        flexDirection: 'column',
        paddingLeft: '1vh',
    },
    clothingInnerContainerInputWrapper: {
        display: 'flex',
        flexDirection: 'unset',
        paddingLeft: '1vh',
        paddingBottom: '1vh',
    },
    clothingLeftSidebar: {
        display: 'flex',
        alignItems: 'flex-end',
        flexDirection: 'column',
        width: '100px',
        height: '100%',
    },
    clothingLeftSideBarTab: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '35%',
        height: '3.5%',
        backgroundColor: 'rgb(34, 40, 49)',
        borderRadius: '3px',
        marginTop: '5%',
        marginRight: '5%',
    },
    clothingMenuContaner: {
        position: 'absolute',
        whiteSpace: 'nowrap',
        right:'0',
        top: '50%',    
        height:'100%',
        transform: 'translate(0%, -50%)',
        display: 'flex',
        alignItems: 'right',
        justifyContent: 'right',
    },
    clothingModalContainer: {
        position: 'absolute',
        whiteSpace: 'nowrap',
        left: '50%',
        top: '50%',    
        transform: 'translate(-50%, -50%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    clothingContainer: {
        display: 'flex',
        width: '402px',
        height: '100%',
        backgroundColor: 'rgb(34, 40, 49)',
        flexDirection: 'column',
    },
    clothingRightSidebar: {
        display: 'flex',
        width: '3.5vw',
        height:'100%'
    },
    clothingRightSidebarInner: {
        display: 'flex',
        justifyContent: 'center',
        flexDirection: 'column',
        width: '100%',
        height: '100%',
        backgroundColor: '#30475e',
    },
    clothingRightSidebarIcon: {
        display: 'flex',
        justifyContent: 'center',
        paddingTop: '1vh',
        paddingBottom: '0.5vh',
    },
    clothingRightSidebarTabs: {
        display: 'flex',
        height: '100%',
        alignItems: 'center',
        flexDirection: 'column',
    },
    clothingRightSidebarTab: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '5.5%',
        width: '100%',
        cursor: 'pointer',
    },
    centeredText: {
        textAlign: 'center',
    },
});